# Generated by Django 4.2.2 on 2023-06-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_student_college_student_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
    ]
