# Generated by Django 4.2.2 on 2023-06-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_rename_name_course_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='workingprofesional',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='donations',
            name='last_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workingprofesional',
            name='last_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
