# Generated by Django 4.2.2 on 2023-06-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_rename_full_name_donations_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id_card',
        ),
    ]
