# Generated by Django 4.2.2 on 2023-06-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_remove_student_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_card'),
        ),
    ]
