# Generated by Django 4.2.2 on 2023-06-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_student_id_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='amount',
        ),
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(default='waiting', max_length=100),
        ),
        migrations.AddField(
            model_name='workingprofesional',
            name='working_professional_status',
            field=models.CharField(default='waiting', max_length=100),
        ),
    ]
