# Generated by Django 4.2.2 on 2023-06-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_remove_donations_amount_student_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='chapter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
