# Generated by Django 4.2.2 on 2023-07-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_student_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetsTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('name_of_purpose', models.CharField(blank=True, max_length=500, null=True)),
                ('status_of_lets_talk', models.CharField(default='waiting', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
