# Generated by Django 4.2.2 on 2023-07-04 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_committeeparticipation_leadershipposition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsAndPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_title', models.TextField(blank=True, null=True)),
                ('meta_title', models.TextField(blank=True, max_length=500, null=True)),
                ('meta_discription', models.TextField(blank=True, null=True)),
                ('events_and_programs_image', models.ImageField(blank=True, null=True, upload_to='events_and_programs_images')),
                ('meta_keyword', models.TextField(blank=True, max_length=500, null=True)),
                ('events_and_programs_image_url', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('status_record', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_and_program_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
