# Generated by Django 4.2.2 on 2023-07-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_eventsandprograms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsandprograms',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
