# Generated by Django 4.2.2 on 2023-07-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_alter_eventsandprograms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='type_of_id_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
